### ISSUE TITLE
CFBundleTypeOSTypes capability for bundledocument

### ISSUE THREAD

**Issue by Vampire** [TheInfiniteKind/appbundler#50]
bundledocument should support a comma-separated attribute that is translated to a string-array with key `CFBundleTypeOSTypes`.

**Comment by sreilly** [comment]
would it be preferable to support the UTI-based LSItemContentTypes?

**Comment by Vampire** [comment]
Those are already supported.
Do they exclude each other?
Until now we had both in our plist.

**Comment by sreilly** [comment]
According to Apple LSItemContentTypes takes precedence over CFBundleTypeOSTypes.  I take that to mean that both would be useful.  Would you be interested in adding these to appbundler?

**Comment by Vampire** [comment]
Ah, well, it is deprecated since 2007 and ignored if `LSItemContentTypes` is given, so let's just ignore that I said anything. :-)
