### ISSUE TITLE
encoding problem when writing plist file

### ISSUE THREAD

**Issue by Vampire** [TheInfiniteKind/appbundler#52]
The plist is written to disk in the system default encoding, but no encoding is noted in the XML.
The default encoding of an XML file if no encoding is specified is UTF-8.
So the contents written are not encoded properly if you use characters from outside ASCII, like the copyright character or some special characters in names or similar.
One option would be to add the encoding as attribute to the generated plist file, but the preferable option would be to explictily specify UTF-8 as encoding when writing the file.

**Comment by sreilly** [comment]
Thanks @Vampire for the fix in PR #53
