### ISSUE TITLE
The native binary is created as universal (32/64) wrong?

### ISSUE THREAD

**Issue by Vampire** [TheInfiniteKind/appbundler#56]
The Readme says `The native binary is created as universal (32/64)`, but if I send it through `file` it tells me it is only a 64-bit executable, not universal.
Either the build, or the readme should be updated.

**Comment by sreilly** [comment]
Yes, the readme needs to be updated.  It's not possible to create 32 bit java builds on macOS with any recent JVM.

**Comment by sreilly** [comment]
Fixed in readme.  Thanks for the suggestion!
