### ISSUE TITLE
OpenJDK version problem

### ISSUE THREAD

**Issue by jfr85** [TheInfiniteKind/appbundler#60]
Hi!

I have a problem with the latest version of the AppBundler:

When I create a .app file with this bundler all goes well when I 
include a runnable jar file that has been compiled with OpenJDK8.
But when I build the same runnable jar file with OpenJDK10 I get 
the following error message when trying to run the resulting .app:

Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: mytest/main has been compiled by a more recent version of the Java Runtime (class file version 54.0), this version of the Java Runtime only recognizes class file versions up to 52.0

I created the jar by exporting it from Eclipse as a runnable jar file.

What can I do about it? Or could this be an issue?

**Comment by sreilly** [comment]
Hello! What version of the JVM are you bundling with the app? It sounds like it's older than v10

**Comment by sreilly** [comment]
closing as it sounds like the bundled runtime is older than v10
